language: elixir
before_install:
  - sudo apt-get install -y inotify-tools
otp_release:
  - 18.0
elixir:
  - 1.1.0
env:
  - MIX_ENV=test
script:
  - mix local.hex --force
  - mix deps.get
  - mix compile --warnings-as-errors
  - mix test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cad77fdb5cda2050ced8
    on_success: change
    on_failure: always
    on_start: false